"""empty message

Revision ID: 0eb5aaf0029e
Revises: 
Create Date: 2023-01-27 17:09:16.095599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb5aaf0029e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('corporate_registration_number', sa.Integer(), nullable=True),
    sa.Column('clinic_name', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialist_license_number', sa.Integer(), nullable=True),
    sa.Column('specialist_img', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('profile',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('idx_user', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=200), nullable=True),
    sa.Column('profile_img', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idx_user'], ['user.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('user')
    # ### end Alembic commands ###
