"""empty message

Revision ID: 522f173f692e
Revises: 0eb5aaf0029e
Create Date: 2023-01-30 10:59:34.003123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522f173f692e'
down_revision = '0eb5aaf0029e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
